const types = {
    FETCHING_CHATS_START:' FETCHING_CHATS_START',
    FETCHING_CHATS_FAIL:'FETCHING_CHATS_FAIL',
    FETCHING_CHATS_SUCCECED:'FETCHING_CHATS_SUCCECED',

    FETCHING_CHAT_START:"FETCHING_CHAT_START",
    FETCHING_CHAT_FAIL:"FETCHING_CHAT_FAIL",
    FETCHING_CHAT_SUCCECED:'FETCHING_CHAT_SUCCECED',

    
    GET_CHAT_PARTNER_START: 'GET_CHAT_PARTNER_START',
    GET_CHAT_PARTNER_SUCCECED: 'GET_CHAT_PARTNER_SUCCECED',
    GET_CHAT_PARTNER_FAIL: 'GET_CHAT_PARTNER_FAIL',
    
    GET_ROOM_START: 'GET_ROOM_START',
    GET_ROOM_SUCCECED: 'GET_ROOM_SUCCECED',
    GET_ROOM_FAIL: 'GET_ROOM_FAIL',
    
    GET_MESSAGES_START: 'GET_MESSAGES_START',
    GET_MESSAGES_SUCCECED: 'GET_MESSAGES_SUCCECED',
    GET_MESSAGES_FAIL: 'GET_MESSAGES_FAIL'
    
}



export default types