const types = {
    FETCHING_CHATS_START:' FETCHING_CHATS_START',
    FETCHING_CHATS_FAIL:'FETCHING_CHATS_FAIL',
    FETCHING_CHATS_SUCCEED:'FETCHING_CHATS_SUCCEED',

    FETCHING_CHAT_START:"FETCHING_CHAT_START",
    FETCHING_CHAT_FAIL:"FETCHING_CHAT_FAIL",
    FETCHING_CHAT_SUCCEED:'FETCHING_CHAT_SUCCEED',

    
    GET_CHAT_PARTNER_START: 'GET_CHAT_PARTNER_START',
    GET_CHAT_PARTNER_SUCCEED: 'GET_CHAT_PARTNER_SUCCEED',
    GET_CHAT_PARTNER_FAIL: 'GET_CHAT_PARTNER_FAIL',
    
    GET_ROOM_START: 'GET_ROOM_START',
    GET_ROOM_SUCCEED: 'GET_ROOM_SUCCEED',
    GET_ROOM_FAIL: 'GET_ROOM_FAIL',
    
    GET_MESSAGES_START: 'GET_MESSAGES_START',
    GET_MESSAGES_SUCCEED: 'GET_MESSAGES_SUCCEED',
    GET_MESSAGES_FAIL: 'GET_MESSAGES_FAIL',
    
    SET_CHAT_DATA:'SET_CHAT_DATA',
    UPDATE_MESSAGE:'UPDATE_MESSAGE',
    SEEN_MESSAGE:'SEEN_MESSAGE'
}



export default types