 export const provinces = [
    "select province",
    "Eastern Cape",
    "Free State",
    "Gauteng",
    "KwaZulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "Northern Cape",
    "North West",
    "Western Cape",
  ];
  
 export  const ObjectCities = {
    "Eastern Cape": [
      'Alice',
      'Butterworth',
      'East London',
      'Graaff-Reinet',
      'Grahamstown',
      'King William’s Town',
      'Mthatha',
      'Port Elizabeth',
      'Queenstown',
      'Uitenhage',
      'Zwelitsha'
    ],
    "Free State": [
      'Bethlehem',
      'Bloemfontein',
      'Jagersfontein',
      'Kroonstad',
      'Odendaalsrus',
      'Parys',
      'Phuthaditjhaba',
      'Sasolburg',
      'Virginia',
      'Welkom'
    ],
    Gauteng: [
      'Benoni',
      'Boksburg',
      'Brakpan',
      'Carletonville',
      'Germiston',
      'Johannesburg',
      'Krugersdorp',
      'Pretoria',
      'Randburg',
      'Randfontein',
      'Roodepoort',
      'Soweto',
      'Springs',
      'Vanderbijlpark',
      'Vereeniging',
    ],
    "KwaZulu-Natal": [
      'Durban',
      'Empangeni',
      'Ladysmith',
      'Newcastle',
      'Pietermaritzburg',
      'Pinetown',
      'Ulundi',
      'Umlazi',
    ],
    Limpopo: [
      'Giyani',
      'Lebowakgomo',
      'Musina',
      'Phalaborwa',
      'Polokwane',
      'Seshego',
      'Sibasa',
      'Thabazimbi',
    ],
    Mpumalanga: [
      'Emalahleni',
      'Nelspruit',
      'Secunda',
    ],
    "Northern Cape": [
      
      'Kimberley',
  'Kuruman',
  'Port Nolloth',
    ],
    "North West": [
      'Klerksdorp',
      'Mahikeng',
      'Mmabatho',
      'Potchefstroom',
      'Rustenburg',
    ],
    "Western Cape": [
      'Bellville',
      'Cape Town',
      'Constantia',
      'George',
      'Hopefield',
      'Oudtshoorn',
      'Paarl',
      'Simon’s Town',
      'Stellenbosch',
      'Swellendam',
      'Worcester',
    ],
  };
  