const dataTypes = {
    FILTER_DATA:"FILTER_DATA",
    
    FETCHING_PROFILES_START:'FETCHING_PROFILES_START',
    FETCHING_PROFILES_SUCCEED:'FETCHING_PROFILES_SUCCEED',
    FETCHING_PROFILES_FAIL:'FETCHING_PROFILES_FAIL',
    FETCHING_MORE_PROFILES_START:'FETCHING_MORE_PROFILES_START',
    FETCHING_MORE_PROFILES_SUCCEED:'FETCHING_MORE_PROFILES_SUCCEED',
    FETCHING_MORE_PROFILES_FAIL:'FETCHING_MORE_PROFILES_FAIL',

    FETCHING_FilTER_DATA_START:'FETCHING_FilTER_DATA_START',
    FETCHING_FilTER_DATA_SUCCEED:'FETCHING_FilTER_DATA_SUCCEED',
    FETCHING_FilTER_DATA_FAIL:'FETCHING_FilTER_DATA_FAIL',
    
   
}



export default dataTypes