const dataTypes = {
    FILTER_DATA:"FILTER_DATA",
    
    FETCHING_PROFILES_START:'FETCHING_PROFILES_START',
    FETCHING_PROFILES_SUCCECED:'FETCHING_PROFILES_SUCCECED',
    FETCHING_PROFILES_FAIL:'FETCHING_PROFILES_FAIL',

    FETCHING_FilTER_DATA_START:'FETCHING_FilTER_DATA_START',
    FETCHING_FilTER_DATA_SUCCECED:'FETCHING_FilTER_DATA_SUCCECED',
    FETCHING_FilTER_DATA_FAIL:'FETCHING_FilTER_DATA_FAIL'
}



export default dataTypes