const types = {
    GET_USER_START: 'GET_USER_START',
    GET_USER_FAIL: 'GET_USER_FAIL',
    GET_USER_SUCCECEED: 'GET_USER_SUCCECEED',

    LOG_IN_START: "LOG_IN_START",
    LOG_IN_FAIL: "LOG_IN_FAIL",
    LOG_IN_SUCCECEED: "LOG_IN_SUCCECEED",
    
    LOG_OUT:'LOG_OUT',

    FETCH_USER_PROFILE_START: "FETCH_USER_PROFILE_START",
    FETCH_USER_PROFILE_FAIL: "FETCH_USER_PROFILE_FAIL",
    FETCH_USER_PROFILE_SUCCECEED: "FETCH_USER_PROFILE_SUCCECEED",
   
    UPDATE_USER_PROFILE_START: "UPDATE_USER_PROFILE_START",
    UPDATE_USER_PROFILE_FAIL: "UPDATE_USER_PROFILE_FAIL",
    UPDATE_USER_PROFILE_SUCCECEED: "UPDATE_USER_PROFILE_SUCCECEED",
    
    UPDATE_USER_NOTICATIONS: "UPDATE_USER_NOTICATIONS",
    CLEAR_USER_NOTICATIONS: "CLEAR_USER_NOTICATIONS",

    TOGGLE_SLIDE_IN_LEFT:'TOGGLE_SLIDE_IN_LEFT',
    TOGGLE_SLIDE_IN_RIGHT:'TOGGLE_SLIDE_IN_RIGHT',

    SET_SEARCHED_PROFILE: 'SET_SEARCHED_PROFILE'
}

export default types