const types = {
    GET_USER_START: 'GET_USER_START',
    GET_USER_FAIL: 'GET_USER_FAIL',
    GET_USER_SUCCECEDED: 'GET_USER_SUCCECEDED',

    LOG_IN_START: "LOG_IN_START",
    LOG_IN_FAIL: "LOG_IN_FAIL",
    LOG_IN_SUCCECEDED: "LOG_IN_SUCCECEDED",

    FETCH_USER_PROFILE_START: "FETCH_USER_PROFILE_START",
    FETCH_USER_PROFILE_FAIL: "FETCH_USER_PROFILE_FAIL",
    FETCH_USER_PROFILE_SUCCECEDED: "FETCH_USER_PROFILE_SUCCECEDED"

   

}

export default types